import sys
import os
import json

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from sentence_transformers import SentenceTransformer

CHROMA_PERSIST_DIR = os.environ.get("CHROMA_PERSIST_DIR", "./chroma_db")

AI_ML_CHUNKS = [
    {
        "topic": "supervised_learning_fundamentals",
        "text": """Supervised learning is the dominant paradigm in machine learning, where a model learns a mapping from inputs to outputs by training on labeled examples. The learning process minimizes a loss function that measures the discrepancy between predicted outputs and ground truth labels. Given a dataset of input-output pairs, the model generalizes from the training examples to unseen data. This generalization ability is the core goal of supervised learning. Common supervised tasks include regression, where the output is a continuous value, and classification, where the output belongs to one of several discrete categories. The choice of model architecture, loss function, and optimization algorithm depends heavily on the task structure and data characteristics. For regression tasks, mean squared error is the typical loss, while cross-entropy loss is standard for classification. Understanding when and why to use each formulation is fundamental to building effective ML systems.""",
    },
    {
        "topic": "bias_variance_tradeoff",
        "text": """The bias-variance tradeoff describes the tension between a model's ability to fit training data and its ability to generalize to new data. Bias refers to the systematic error introduced by a model's assumptions — a high-bias model is overly simplistic and underfits the training data. Variance refers to the model's sensitivity to fluctuations in training data — a high-variance model overfits by capturing noise as if it were signal. Adding model complexity generally reduces bias but increases variance. Regularization techniques like L1 (Lasso) and L2 (Ridge) penalties constrain model parameters to reduce variance at the cost of a small increase in bias. The optimal model minimizes total error, which is the sum of bias squared, variance, and irreducible noise. In practice, this tradeoff guides decisions about model depth, feature engineering, and regularization strength. Cross-validation provides an empirical estimate of generalization error, helping practitioners navigate this tradeoff without access to a true test distribution.""",
    },
    {
        "topic": "neural_network_architecture",
        "text": """A neural network is a layered computational graph where each layer applies a learned linear transformation followed by a nonlinear activation function. The input layer receives raw features, intermediate hidden layers extract progressively abstract representations, and the output layer produces the final prediction. The depth of the network (number of layers) and width (number of neurons per layer) determine its representational capacity. Deep networks can represent complex hierarchical patterns that shallow networks cannot, which explains their success on tasks like image recognition and natural language processing. A key design choice is the activation function: ReLU (Rectified Linear Unit) is most widely used because it does not suffer from the vanishing gradient problem that plagued sigmoid and tanh activations in deep networks. Batch normalization stabilizes training by normalizing layer inputs, enabling faster convergence and higher learning rates. Dropout regularizes the network by randomly deactivating a fraction of neurons during each training step, preventing co-adaptation and acting as an implicit ensemble.""",
    },
    {
        "topic": "backpropagation",
        "text": """Backpropagation is the algorithm used to compute gradients of the loss function with respect to every parameter in a neural network. It applies the chain rule of calculus by performing two passes over the computational graph: a forward pass that computes layer-by-layer activations and the final loss, and a backward pass that propagates gradients from the output back to the input. During backpropagation, each layer receives the gradient of the loss with respect to its output and must compute two quantities: the gradient with respect to its parameters (used for the weight update) and the gradient with respect to its input (passed to the previous layer). This recursive structure makes backpropagation efficient because each gradient is computed exactly once. Numerically, modern deep learning frameworks use automatic differentiation to implement backpropagation without requiring manual derivation of gradients. Understanding backpropagation is essential for debugging training instability, designing new architectures, and reasoning about gradient flow in very deep networks.""",
    },
    {
        "topic": "transformer_architecture",
        "text": """The Transformer architecture, introduced in "Attention Is All You Need" (Vaswani et al., 2017), replaced recurrent sequence models with a fully attention-based design. The core innovation is the multi-head self-attention mechanism, which allows each position in a sequence to directly attend to every other position, computing weighted combinations based on learned query-key compatibility scores. This removes the sequential dependency of RNNs, enabling full parallelism during training. A Transformer block consists of a multi-head attention sublayer followed by a position-wise feed-forward network, with residual connections and layer normalization applied after each sublayer. Positional encodings are added to token embeddings to inject sequence order information since attention is permutation-invariant. Stacking many such blocks builds increasingly abstract representations. The encoder processes the input sequence while the decoder generates outputs autoregressively, attending to both its own previous outputs and the encoder's representations. This architecture is the foundation for BERT, GPT, T5, and virtually all modern large language models.""",
    },
    {
        "topic": "attention_mechanism",
        "text": """The attention mechanism computes a weighted sum of value vectors, where the weights are derived from the compatibility between query vectors and key vectors. In the scaled dot-product formulation, compatibility is computed as the dot product of the query and key, scaled by the square root of the key dimension to prevent gradients from vanishing in high-dimensional spaces, then normalized with a softmax to produce a probability distribution over positions. Multi-head attention runs this operation in parallel across multiple learned projection subspaces, allowing the model to simultaneously attend to information from different representation subspaces at different positions. Self-attention applies the mechanism within a single sequence — each token attends to all other tokens — enabling the model to build contextual representations that capture long-range dependencies without the path-length limitations of RNNs. Cross-attention, used in encoder-decoder architectures, allows the decoder to attend to encoder outputs. The attention weights are interpretable and have been used to analyze what relationships the model has learned.""",
    },
    {
        "topic": "bert_language_models",
        "text": """BERT (Bidirectional Encoder Representations from Transformers) pre-trains a Transformer encoder on large text corpora using two self-supervised objectives: Masked Language Modeling (MLM) and Next Sentence Prediction (NSP). In MLM, 15% of tokens are randomly masked and the model learns to predict them using context from both directions, unlike GPT which is unidirectional. This bidirectional context produces richer representations useful for understanding tasks. BERT introduced the paradigm of pre-training a large model on unlabeled text and fine-tuning it on downstream labeled tasks with minimal architectural changes. Fine-tuning adds a task-specific head (e.g., a linear classifier for classification tasks) on top of BERT's output and trains the entire model end-to-end on the labeled dataset. This transfer learning approach dramatically reduces the labeled data requirement for achieving strong performance. Variants like RoBERTa removed NSP and used dynamic masking, showing that careful training details significantly impact pre-training quality. Understanding BERT's design principles is essential for working with modern NLP systems.""",
    },
    {
        "topic": "retrieval_augmented_generation",
        "text": """Retrieval-Augmented Generation (RAG) is an architecture that augments a language model's parametric knowledge with non-parametric information retrieved from an external knowledge base at inference time. The pipeline consists of two main components: a retrieval system that fetches relevant documents given a query, and a generation model that conditions its output on both the query and the retrieved context. RAG addresses the key limitations of standalone LLMs: outdated knowledge (since the model weights are fixed after training), hallucination (the model generating plausible but false content), and lack of source attribution. In a typical RAG system, documents are chunked into passages, encoded into dense vector representations using an embedding model, and stored in a vector database. At query time, the query is encoded into the same embedding space and the most semantically similar passages are retrieved via approximate nearest neighbor search. These passages are concatenated with the query and passed to the generation model as context. The quality of a RAG system depends critically on chunking strategy, embedding model quality, retrieval accuracy, and the generator's ability to ground its output in the retrieved context.""",
    },
    {
        "topic": "embeddings_semantic_search",
        "text": """Embedding models map discrete inputs like text or images into dense continuous vector spaces where semantically similar items are close together by some distance metric, typically cosine similarity or dot product. Text embedding models are trained to minimize the distance between semantically related pairs and maximize it for unrelated pairs, often using contrastive loss on large datasets of paired texts. Sentence-transformers, built on top of BERT-like models with mean pooling over token embeddings, are the standard choice for producing high-quality sentence-level embeddings. The quality of embeddings has a direct impact on retrieval quality in RAG systems. Embedding all-MiniLM-L6-v2 is a compact, fast model that performs well on semantic similarity benchmarks while requiring significantly less compute than larger models. When building semantic search systems, the embedding model must be the same at index time and query time, as the vector space it defines is model-specific. Fine-tuning embedding models on domain-specific text can substantially improve retrieval quality for specialized applications.""",
    },
    {
        "topic": "vector_databases",
        "text": """Vector databases are purpose-built storage systems for high-dimensional embedding vectors, optimized for approximate nearest neighbor (ANN) search. Unlike traditional databases that execute exact lookups, vector databases trade a small amount of recall for dramatically faster search at scale using indexing algorithms like HNSW (Hierarchical Navigable Small World) and IVF (Inverted File Index). HNSW constructs a multi-layered graph structure where traversal from sparse upper layers to dense lower layers enables logarithmic-time approximate nearest neighbor search. ChromaDB is an open-source, embeddable vector database designed for LLM applications that supports local persistent storage and integrates directly with embedding functions. Pinecone and Weaviate are managed cloud alternatives that add features like metadata filtering and real-time updates at scale. The key parameters when configuring vector search are the distance metric (cosine, dot product, or Euclidean), the number of results to retrieve (top-k), and index construction parameters that govern the recall-latency tradeoff. In production RAG systems, metadata filtering allows restricting retrieval to specific document types or date ranges before applying vector similarity.""",
    },
    {
        "topic": "model_evaluation_metrics",
        "text": """Evaluating a machine learning model requires careful selection of metrics aligned with the business objective, not just model accuracy. For binary classification, accuracy is misleading on imbalanced datasets — a model predicting the majority class 99% of the time will have high accuracy but be useless. Precision measures the fraction of positive predictions that are correct; recall measures the fraction of actual positives that are identified. The F1 score is the harmonic mean of precision and recall and is a standard summary metric. The precision-recall tradeoff is controlled by the classification threshold, and the area under the PR curve (AUC-PR) summarizes performance across all thresholds. The ROC curve plots true positive rate against false positive rate, and AUC-ROC measures the model's ability to discriminate between classes across all thresholds. For regression, RMSE is sensitive to outliers while MAE is more robust. For information retrieval tasks common in RAG evaluation, Mean Reciprocal Rank (MRR), Normalized Discounted Cumulative Gain (NDCG), and Recall@K measure the quality of retrieved results. Choosing the right metric requires understanding the cost asymmetry between false positives and false negatives in the application.""",
    },
    {
        "topic": "overfitting_regularization",
        "text": """Overfitting occurs when a model learns the training data too well, including its noise and irrelevant patterns, resulting in poor generalization to new data. The gap between training and validation loss is the clearest diagnostic signal. L2 regularization (weight decay) adds a penalty proportional to the squared magnitude of weights to the loss function, encouraging smaller weights and smoother decision boundaries. L1 regularization adds a penalty proportional to the absolute value of weights, which has the effect of driving many weights exactly to zero, producing sparse models and acting as implicit feature selection. Dropout randomly sets a fraction of activations to zero during training, forcing the network to learn redundant representations that do not rely on any single neuron. Early stopping monitors validation loss and halts training when it begins to increase, preventing further overfitting at the cost of not fully minimizing training loss. Data augmentation artificially expands the training set by applying label-preserving transformations, reducing overfitting particularly in computer vision. Understanding which regularization technique to apply and when requires knowledge of the model size, dataset size, and the nature of the task.""",
    },
    {
        "topic": "gradient_descent_optimizers",
        "text": """Gradient descent updates model parameters in the direction that minimally decreases the loss by taking a step proportional to the negative gradient. Stochastic gradient descent (SGD) computes gradients on individual training examples, introducing noise that can help escape local minima. Mini-batch SGD is the practical standard, computing gradients on small batches to balance computational efficiency and gradient noise. Momentum accumulates an exponentially decaying running average of past gradients, dampening oscillations and accelerating convergence in directions of consistent gradient. Adam (Adaptive Moment Estimation) combines momentum with adaptive per-parameter learning rates by maintaining running estimates of both the first moment (mean) and second moment (uncentered variance) of gradients. Adam typically converges faster than SGD with momentum, but can generalize slightly worse in some settings. The learning rate is the most critical hyperparameter: too large causes divergence, too small causes slow convergence. Learning rate schedules like cosine annealing or step decay reduce the learning rate over training to refine the solution. Gradient clipping caps the gradient norm before applying the update, preventing exploding gradients in recurrent networks and other architectures with deep computational graphs.""",
    },
    {
        "topic": "transfer_learning_finetuning",
        "text": """Transfer learning leverages representations learned on one task or domain to improve performance on a different but related task, especially when labeled data for the target task is scarce. The intuition is that lower-level features learned on large datasets (edges in vision, syntactic patterns in NLP) are general and reusable across tasks, while higher-level features are task-specific and must be adapted. In the standard fine-tuning paradigm, a pre-trained model is loaded with its weights, a task-specific head is attached (e.g., a classification layer), and the entire model is trained end-to-end on the labeled target dataset with a small learning rate to avoid destroying the pre-trained representations. Feature extraction is an alternative where pre-trained weights are frozen and only the task-specific head is trained. This is faster but less flexible than full fine-tuning. Parameter-efficient fine-tuning methods like LoRA (Low-Rank Adaptation) inject small trainable adapter modules into the pre-trained model, enabling adaptation with a fraction of the trainable parameters, which is critical for fine-tuning very large language models under compute constraints. Domain-adaptive pre-training, where the pre-trained model is further pre-trained on unlabeled domain-specific text before fine-tuning, often provides additional gains in specialized domains.""",
    },
    {
        "topic": "large_language_models",
        "text": """Large language models (LLMs) are autoregressive Transformer decoders trained on web-scale text corpora to predict the next token given all previous tokens. At sufficient scale, these models exhibit emergent capabilities: in-context learning (solving novel tasks from a few examples in the prompt without weight updates), chain-of-thought reasoning, and code generation. In-context learning works by framing the task as a continuation of a structured prompt, leveraging the model's compressed knowledge of language and world patterns. Instruction fine-tuning adapts base language models to follow natural language instructions by training on curated datasets of instruction-response pairs. Reinforcement Learning from Human Feedback (RLHF) further aligns model outputs with human preferences by using a reward model trained on human comparisons to provide a training signal for policy optimization via PPO. Prompt engineering — the design of input prompts to elicit desired model behaviors — has become a critical skill for practitioners working with LLMs. Techniques like zero-shot prompting, few-shot prompting, chain-of-thought prompting, and structured output prompting significantly impact model performance. Understanding the failure modes of LLMs — hallucination, sycophancy, context length limitations — is essential for building reliable systems.""",
    },
    {
        "topic": "convolutional_neural_networks",
        "text": """Convolutional Neural Networks (CNNs) exploit the spatial structure of image data through weight sharing and local connectivity. A convolutional layer applies a learned filter by computing the dot product between the filter weights and a local patch of the input, sliding across the input to produce a feature map that captures the presence of the learned pattern at each spatial location. Multiple filters in a single layer detect different patterns simultaneously. Pooling layers (max or average) downsample feature maps, reducing spatial resolution while increasing the receptive field and providing some translation invariance. Deep CNNs stack convolution and pooling layers to build hierarchical representations: early layers detect edges and textures, middle layers detect shapes and object parts, and late layers capture high-level semantic concepts. Architectures like ResNet introduced residual connections that allow gradients to flow directly through skip connections, enabling training of very deep networks (100+ layers) that would otherwise suffer from the degradation problem. Batch normalization in CNNs normalizes activations per channel, stabilizing training and enabling higher learning rates. Understanding CNN architecture design — filter size, stride, padding, and the depth-width tradeoff — is core knowledge for computer vision practitioners.""",
    },
    {
        "topic": "reinforcement_learning",
        "text": """Reinforcement learning (RL) is a framework where an agent learns to make decisions by interacting with an environment to maximize cumulative reward over time. The agent observes the current state, selects an action according to its policy, receives a reward signal, and transitions to a new state. The goal is to learn a policy that maximizes expected cumulative discounted reward. The Markov Decision Process (MDP) formalism provides the mathematical framework for RL, requiring the Markov property: the next state depends only on the current state and action, not on history. Value-based methods like Q-learning estimate the expected return from each state-action pair, and the agent acts greedily with respect to these Q-values. Deep Q-Networks (DQN) parameterize the Q-function with a neural network and use experience replay and a target network to stabilize training. Policy gradient methods directly optimize the policy by estimating the gradient of expected return with respect to policy parameters. Actor-critic methods combine both approaches: the actor is the policy network and the critic estimates the value function to reduce gradient variance. Proximal Policy Optimization (PPO) is the most widely used RL algorithm, applying a clipped surrogate objective that prevents destructively large policy updates.""",
    },
    {
        "topic": "mlops_deployment",
        "text": """MLOps refers to the practices, tools, and culture for reliably deploying and maintaining machine learning models in production. The ML lifecycle includes data collection and validation, feature engineering, model training and evaluation, deployment, and monitoring. Unlike traditional software, ML systems have additional failure modes: data drift (the distribution of incoming data changes over time), concept drift (the relationship between features and labels changes), and model degradation (performance decays as the world changes). Model serving infrastructure must balance latency, throughput, and resource utilization. Batch inference processes large volumes of predictions offline, while online inference serves real-time requests. Canary deployments gradually route a fraction of traffic to a new model version, limiting blast radius if performance regresses. A/B testing compares model versions by splitting live traffic and measuring business metrics. Experiment tracking with tools like MLflow or Weights & Biases records hyperparameters, metrics, and artifacts for each training run, enabling reproducibility and comparison. Feature stores centralize feature computation and serving, ensuring consistency between training and serving environments — one of the most common sources of production failures in ML systems.""",
    },
    {
        "topic": "random_forests_ensemble",
        "text": """Random forests are an ensemble method that builds many decision trees on bootstrap samples of the training data and averages their predictions. Each split in each tree is chosen from a random subset of features, introducing diversity among trees and reducing correlation between them. The final prediction for regression is the mean of tree predictions; for classification it is the majority vote. The randomness introduced by bootstrap sampling (bagging) and random feature subsets reduces variance compared to a single tree without increasing bias. Feature importance in random forests is typically measured by the total reduction in impurity (Gini impurity for classification, variance for regression) achieved by splits on each feature, aggregated across all trees. Gradient boosting builds trees sequentially, with each tree fitting the residuals of the ensemble so far. XGBoost and LightGBM implement highly optimized gradient boosting with regularization, parallel split finding, and histogram-based tree construction, making them the dominant choice for tabular data competitions and production systems. Understanding when ensemble methods outperform single models and how to tune the key hyperparameters (number of trees, max depth, learning rate for boosting, min samples per leaf) is essential for applied ML work.""",
    },
    {
        "topic": "feature_engineering",
        "text": """Feature engineering is the process of transforming raw data into representations that enable machine learning models to learn effectively. It remains one of the most impactful activities in applied ML, often contributing more to model performance than the choice of algorithm. Numeric features typically require scaling: standardization (zero mean, unit variance) is appropriate for algorithms that assume Gaussian distributions or use distance metrics, while min-max normalization maps features to a fixed range and is preferable when the distribution is known and bounded. Categorical features must be converted to numeric representations: one-hot encoding works for low-cardinality features, while target encoding (replacing category with the mean target value) handles high-cardinality features but requires care to avoid data leakage. Interaction features capture non-linear relationships by multiplying two or more features. Temporal features derived from timestamps (hour of day, day of week, time since event) are critical for time-series and event-based models. Missing value imputation strategies — mean/median imputation, forward-fill for time series, or learning imputation from a separate model — significantly impact model robustness. Domain knowledge drives the most impactful feature engineering decisions, translating business understanding into predictive signals.""",
    },
]

BACKEND_CHUNKS = [
    {
        "topic": "rest_api_design",
        "text": """REST (Representational State Transfer) is an architectural style for distributed hypermedia systems, not a protocol. RESTful APIs use HTTP methods semantically: GET retrieves resources without side effects (idempotent and safe), POST creates new resources or triggers non-idempotent operations, PUT replaces a resource entirely, PATCH applies partial updates, and DELETE removes resources. Resource URLs should be nouns representing entities, not verbs describing actions: /users/42/orders not /getUserOrders. Response status codes communicate meaning: 200 OK for successful GET, 201 Created for successful POST, 204 No Content for DELETE, 400 Bad Request for invalid input, 401 Unauthorized when authentication is missing, 403 Forbidden when authenticated but not authorized, 404 Not Found for missing resources, 409 Conflict for state violations, and 500 Internal Server Error for unexpected failures. JSON is the standard response format. Pagination is essential for list endpoints: cursor-based pagination is preferable to offset-based for large datasets because it handles concurrent writes without skipping or duplicating records. API design is a contract — once published, breaking changes (removing fields, changing types) require versioning.""",
    },
    {
        "topic": "database_design_normalization",
        "text": """Database normalization is the process of organizing relational schemas to minimize redundancy and improve data integrity. First Normal Form (1NF) requires atomic values and no repeating groups. Second Normal Form (2NF) requires that all non-key attributes depend on the entire primary key, not just part of it. Third Normal Form (3NF) requires that non-key attributes depend only on the primary key, not on other non-key attributes (no transitive dependencies). The Boyce-Codd Normal Form (BCNF) strengthens 3NF for cases with overlapping candidate keys. In practice, denormalization is often appropriate for read-heavy workloads where join overhead becomes a bottleneck — storing derived or redundant data trades storage and write complexity for read performance. Choosing between a normalized schema and a denormalized one requires understanding the read-write ratio, query patterns, and acceptable consistency tradeoffs. Foreign keys enforce referential integrity at the database level, preventing orphaned records. Indexes accelerate queries but slow writes and increase storage; the right indexing strategy depends on which columns appear in WHERE clauses, JOIN conditions, and ORDER BY clauses in production queries.""",
    },
    {
        "topic": "indexing_query_optimization",
        "text": """Database indexes are data structures, typically B-tree or hash-based, that allow the database engine to locate rows matching a condition without scanning the entire table. A B-tree index supports range queries, equality lookups, and sorting efficiently. A composite index on (col_a, col_b) is useful for queries filtering on both columns, but only the leftmost prefix can be used for range scans. Covering indexes include all columns referenced in a query, allowing the engine to satisfy the query entirely from the index without accessing the main table (index-only scan). The query optimizer uses table statistics to choose between sequential scans and index scans based on selectivity — a highly selective condition (returning few rows) benefits from an index while a low-selectivity condition may be better served by a full table scan. EXPLAIN (or EXPLAIN ANALYZE in PostgreSQL) reveals the query execution plan and is the essential tool for identifying slow queries. Common optimizations include adding missing indexes, rewriting correlated subqueries as joins, and avoiding functions on indexed columns in WHERE clauses which prevent index usage. N+1 query problems — fetching a list then making one query per item — are a frequent ORM-related bottleneck that eager loading or batch queries resolve.""",
    },
    {
        "topic": "nosql_databases",
        "text": """NoSQL databases abandon the relational model to achieve different tradeoffs around scalability, flexibility, and consistency. Document stores like MongoDB store data as self-contained JSON documents, allowing flexible schemas that evolve without migrations. This is well-suited for heterogeneous data but lacks strong consistency guarantees across documents and makes cross-document joins expensive. Key-value stores like Redis are optimized for sub-millisecond reads and writes on simple lookups, making them ideal for caching, session storage, and rate limiting. Column-family stores like Cassandra distribute data across nodes by partition key, enabling massive write throughput and horizontal scaling, but require queries to be designed around known access patterns at schema time. Graph databases like Neo4j store entities and relationships as nodes and edges, enabling efficient traversal of highly connected data like social networks or recommendation graphs. The CAP theorem states that a distributed system can provide at most two of: Consistency, Availability, and Partition tolerance. In practice, partition tolerance is required in distributed systems, so the real choice is between consistency and availability during network failures. Understanding these tradeoffs guides the choice between SQL and various NoSQL systems.""",
    },
    {
        "topic": "caching_strategies",
        "text": """Caching stores the results of expensive computations or frequent data retrievals so subsequent requests can be served from fast storage rather than recomputing or re-fetching. Redis is the standard in-memory cache, supporting strings, hashes, lists, sorted sets, and atomic operations, with configurable TTL (time-to-live) for cache expiration. Cache-aside (lazy loading) is the most common pattern: the application checks the cache first, and on a miss fetches from the database, stores the result in cache, and returns it. Write-through caching writes to the cache and database simultaneously on every write, ensuring cache consistency at the cost of write latency. Write-behind caching buffers writes in the cache and asynchronously flushes them to the database, improving write throughput but risking data loss on cache failure. Cache invalidation — determining when cached data is stale — is the hardest problem in caching. TTL-based invalidation is simple but can serve stale data within the TTL window. Event-driven invalidation explicitly removes or updates cache entries when the underlying data changes, requiring coordination between services. Cache warming pre-populates the cache before traffic hits to prevent thundering herd problems during deployments or restarts.""",
    },
    {
        "topic": "microservices_architecture",
        "text": """Microservices architecture decomposes an application into a collection of small, independently deployable services, each responsible for a specific business capability. Each service owns its data store, avoiding shared databases that create tight coupling. Services communicate via synchronous request-response (HTTP/REST, gRPC) or asynchronous messaging (Kafka, RabbitMQ). The main advantages over a monolith are independent deployability (a team can deploy one service without coordinating with others), technology heterogeneity (different services can use different languages and databases), and fault isolation (a failure in one service does not necessarily cascade to others). The tradeoffs are significant: distributed systems introduce network latency and failure modes that don't exist in monoliths, operational complexity increases dramatically (service discovery, distributed tracing, multiple deployment pipelines), and data consistency across services requires careful design using patterns like sagas. Service meshes like Istio handle cross-cutting concerns like mutual TLS, load balancing, circuit breaking, and observability between services. The decision to adopt microservices should be driven by organizational structure and deployment velocity requirements, not technical novelty — a well-structured monolith is often the right starting point.""",
    },
    {
        "topic": "authentication_authorization",
        "text": """Authentication verifies who a user is; authorization determines what they are allowed to do. JWT (JSON Web Tokens) are a stateless authentication mechanism: the server issues a signed token containing claims (user ID, roles, expiration) and the client sends it with each request. The server verifies the signature using a shared secret (HMAC) or public/private key pair (RSA, ECDSA), without needing to query a database on each request. This enables horizontal scaling but makes token revocation difficult — the token remains valid until expiration. Short-lived access tokens (15 minutes) paired with longer-lived refresh tokens (7 days) balance security and usability. OAuth2 is an authorization delegation protocol that allows a user to grant a third-party application limited access to their account without sharing credentials. OpenID Connect builds on OAuth2 to provide identity (authentication) information in addition to authorization. Role-based access control (RBAC) assigns permissions to roles, and users are assigned roles. Attribute-based access control (ABAC) makes access decisions based on attributes of the user, resource, and environment, enabling finer-grained policies. Passwords must be stored as bcrypt or Argon2 hashes, never in plain text or with reversible encryption. Rate limiting login endpoints and enforcing MFA are essential defenses against credential stuffing attacks.""",
    },
    {
        "topic": "async_programming_python",
        "text": """Asynchronous programming in Python using asyncio enables concurrency without threads, by allowing a single-threaded event loop to switch between tasks when one is waiting for I/O. An async function defined with async def returns a coroutine object; calling it does not execute the body until it is awaited. The await keyword suspends the current coroutine and yields control back to the event loop until the awaited operation completes. This model is highly efficient for I/O-bound workloads like web servers handling many simultaneous connections, because the event loop can serve other requests while waiting for database queries or HTTP calls to return. asyncio.gather runs multiple coroutines concurrently and waits for all to complete. FastAPI is built on Starlette, which uses uvicorn's async ASGI server, and supports both sync and async route handlers. Sync handlers run in a thread pool to avoid blocking the event loop. For CPU-bound work, asyncio provides no parallelism benefit and can actually hurt performance — use multiprocessing or a worker pool instead. Understanding the difference between concurrency (interleaving) and parallelism (simultaneous execution) is critical when designing Python backend systems.""",
    },
    {
        "topic": "message_queues",
        "text": """Message queues decouple producers and consumers, allowing asynchronous processing of work and absorbing traffic spikes without overwhelming downstream services. Apache Kafka is a distributed, durable, high-throughput message log designed for real-time streaming. Producers append events to topics partitioned across brokers, and consumers read from partitions at their own pace with offsets persisted, enabling replay and exactly-once or at-least-once semantics. Kafka is the right choice when you need durability, high throughput, and the ability to replay events from any point in history. RabbitMQ is a traditional message broker with richer routing semantics — exchanges route messages to queues based on topic patterns or headers — and better support for complex pub-sub topologies and priority queues. Celery is a Python task queue that uses Redis or RabbitMQ as a broker and is the standard for background task processing in Python web applications: sending emails, generating reports, processing uploaded files. Dead letter queues capture messages that fail processing after the maximum retry count, enabling manual inspection without losing data. Idempotent message handlers are critical: if a message is delivered more than once (at-least-once semantics), processing it twice must produce the same result as processing it once.""",
    },
    {
        "topic": "system_design_scalability",
        "text": """Designing scalable backend systems requires reasoning about bottlenecks, failure modes, and traffic patterns before writing code. Horizontal scaling adds more servers to handle load; vertical scaling upgrades server hardware. Load balancers distribute incoming requests across multiple instances using algorithms like round-robin, least connections, or consistent hashing. Stateless services scale horizontally without coordination — no server-local session state. Consistent hashing distributes data across nodes such that adding or removing a node only remaps a fraction of keys, minimizing redistribution cost. Database read replicas offload read traffic from the primary but introduce replication lag, making them unsuitable for read-after-write consistency requirements. Sharding partitions data across multiple databases by a partition key; the choice of key determines load distribution — a poor key causes hot spots. Connection pooling limits the number of concurrent database connections, preventing database overload under high concurrency. Circuit breakers detect when a downstream service is failing and temporarily stop sending requests to it, preventing cascade failures. Exponential backoff with jitter in retry logic reduces thundering herd pressure on recovering services. These patterns form the vocabulary for discussing system design in engineering interviews.""",
    },
    {
        "topic": "api_versioning_error_handling",
        "text": """API versioning allows the backend to evolve while supporting existing clients. URL versioning (/v1/users, /v2/users) is the most explicit and widely adopted approach. Header versioning passes the version in an Accept header, keeping URLs clean but making the version less discoverable. Semantic versioning (MAJOR.MINOR.PATCH) communicates the impact of changes: incrementing MAJOR signals breaking changes, MINOR signals backwards-compatible additions, and PATCH signals backwards-compatible bug fixes. Robust error handling communicates what went wrong in a machine-readable format. A consistent error envelope with a code, message, and optional details field allows clients to handle errors programmatically. Validation errors should enumerate all invalid fields, not just the first. Unexpected server errors should return 500 without leaking stack traces or internal details to clients. Structured logging captures request IDs, user IDs, latency, and error codes so that distributed traces can be correlated across services. Request validation at the API boundary using schemas like Pydantic prevents invalid data from reaching business logic and database layers. Input sanitization is distinct from validation — it removes or escapes characters that could be interpreted as code (SQL, HTML, shell commands).""",
    },
]

DATA_SCIENCE_CHUNKS = [
    {
        "topic": "exploratory_data_analysis",
        "text": """Exploratory Data Analysis (EDA) is the process of summarizing and visualizing a dataset to understand its structure, distribution, and relationships before modeling. It uncovers data quality issues (missing values, outliers, duplicates), informs feature engineering decisions, and guides model selection. Descriptive statistics — mean, median, standard deviation, quantiles — characterize the distribution of individual features. The mean is sensitive to outliers; the median is more robust. Histograms and kernel density estimates reveal the shape of distributions. Box plots visualize quartiles and outliers. Scatter plots and correlation matrices reveal pairwise relationships. Heatmaps visualize the correlation matrix, flagging highly correlated features that may cause multicollinearity in linear models. Class distribution analysis is critical for classification: severe imbalance requires resampling or cost-sensitive learning strategies. Missing value analysis examines whether data is missing completely at random (MCAR), missing at random (MAR, conditionally on other observed data), or missing not at random (MNAR, where missingness depends on the unobserved value itself). MNAR is the most problematic case because imputation introduces systematic bias. EDA is iterative — findings often raise new questions that drive additional investigation.""",
    },
    {
        "topic": "cross_validation_model_selection",
        "text": """Cross-validation estimates generalization error by partitioning the dataset into folds, repeatedly training on a subset and evaluating on the held-out portion. K-fold cross-validation splits data into k folds, trains k models each holding out one different fold as the validation set, and averages the validation metrics. This produces a less biased estimate of generalization error than a single train-validation split. Stratified k-fold maintains class proportions across folds, which is essential for imbalanced classification. Time-series cross-validation (walk-forward validation) respects temporal ordering by always training on past data and validating on future data, preventing data leakage from the future. Nested cross-validation uses an outer loop for model evaluation and an inner loop for hyperparameter tuning, providing an unbiased estimate of the tuned model's generalization error. Hyperparameter tuning using the same data that estimated generalization error produces optimistic estimates — the selected hyperparameters are overfitted to the validation set. Model selection should be based on validation performance across multiple folds, and the final model is trained on all available data with the chosen hyperparameters. Hold-out test sets should be used exactly once at the very end, never for iterative model improvement.""",
    },
    {
        "topic": "imbalanced_datasets",
        "text": """Class imbalance — where one class significantly outnumbers others — is common in real-world classification problems: fraud detection, medical diagnosis, anomaly detection. Standard models trained to minimize accuracy on imbalanced data learn to predict the majority class almost exclusively, achieving high accuracy while being useless for the minority class. Evaluation must use class-aware metrics: precision, recall, F1, AUC-PR, and AUC-ROC. Oversampling the minority class (SMOTE creates synthetic samples by interpolating between existing minority samples) increases its representation during training. Undersampling the majority class is simpler but discards potentially useful data. Class weighting adjusts the loss function to penalize misclassification of the minority class more heavily, without changing the dataset. This is the least intrusive approach and is supported natively by most sklearn models via the class_weight parameter. Threshold adjustment — lowering the classification threshold from 0.5 to increase recall at the expense of precision — is appropriate when the cost of false negatives is higher than false positives, as in medical screening. Ensemble methods like BalancedRandomForest and EasyEnsemble combine resampling with ensemble learning. The choice of strategy depends on the degree of imbalance, dataset size, and the relative costs of different error types.""",
    },
    {
        "topic": "statistical_hypothesis_testing",
        "text": """Statistical hypothesis testing provides a framework for making decisions about population parameters from sample data. The null hypothesis (H0) represents the status quo or no-effect assumption; the alternative hypothesis (H1) represents the claim being tested. The p-value is the probability of observing a test statistic as extreme or more extreme than the one computed from the data, assuming H0 is true. A small p-value (typically below 0.05) provides evidence against H0. Common mistakes include treating p-value as the probability that H0 is true (it is not) and treating statistical significance as practical significance (a large dataset can produce highly significant results for trivially small effects). Effect size measures the magnitude of the effect: Cohen's d for means, odds ratio for proportions. The t-test compares means between two groups when data is approximately normally distributed. The Mann-Whitney U test is the non-parametric alternative for non-normal distributions. ANOVA compares means across three or more groups. Chi-squared tests independence between categorical variables. Multiple comparisons inflate the Type I error rate; Bonferroni correction or False Discovery Rate (FDR) control adjusts p-value thresholds accordingly. A/B testing in production is applied hypothesis testing where business metrics serve as the outcome variables.""",
    },
    {
        "topic": "dimensionality_reduction",
        "text": """Dimensionality reduction transforms high-dimensional data into a lower-dimensional representation, addressing the curse of dimensionality where distance metrics become uninformative in very high dimensions. Principal Component Analysis (PCA) finds orthogonal directions (principal components) of maximum variance in the data and projects the data onto the top k components. PCA is a linear method and assumes the most informative structure lies along directions of maximum variance. The explained variance ratio of each component guides the choice of k — retaining 95% of explained variance is a common heuristic. t-SNE (t-Distributed Stochastic Neighbor Embedding) is a non-linear method that preserves local neighborhood structure, making it effective for visualization of high-dimensional data in 2D or 3D. However, t-SNE is non-deterministic, computationally expensive, and distances between clusters in the embedding are not interpretable. UMAP (Uniform Manifold Approximation and Projection) is faster than t-SNE and better preserves global structure. Autoencoders learn a compressed representation (bottleneck) of the input through a neural encoder-decoder pair trained to minimize reconstruction error. Variational autoencoders add a probabilistic latent space that supports smooth interpolation and generation. Dimensionality reduction is used for visualization, noise reduction, and as a preprocessing step to improve downstream model performance and training speed.""",
    },
]

FULLSTACK_CHUNKS = AI_ML_CHUNKS[:5] + BACKEND_CHUNKS[:5] + [
    {
        "topic": "web_performance",
        "text": """Frontend performance directly impacts user experience and business metrics — studies show a 100ms increase in load time correlates with conversion rate drops. Core Web Vitals (LCP, FID/INP, CLS) are Google's standardized metrics for measuring loading, interactivity, and visual stability. Largest Contentful Paint (LCP) measures the time to render the largest visible content element; above 2.5 seconds is poor. Code splitting divides the JavaScript bundle into chunks loaded on demand, reducing the initial bundle size. Tree shaking removes unused code from the final bundle. Image optimization — serving next-gen formats like WebP/AVIF, proper sizing for the display dimensions, and lazy loading below-the-fold images — is typically the highest-impact optimization. Critical CSS, inlined in the HTML head, eliminates render-blocking CSS for above-the-fold content. HTTP/2 multiplexes multiple requests over a single TCP connection, eliminating the per-request connection overhead of HTTP/1.1. CDN (Content Delivery Network) caches static assets at edge locations geographically close to users, reducing latency. Server-side rendering (SSR) and static site generation (SSG) in Next.js send pre-rendered HTML to the browser, improving First Contentful Paint for users on slow connections or devices.""",
    },
    {
        "topic": "nextjs_architecture",
        "text": """Next.js is a React framework that provides file-system-based routing, server-side rendering, static site generation, and API routes out of the box. The App Router (Next.js 13+) uses a directory structure where layout.tsx files define shared UI across routes, page.tsx files define the content for a specific route, and loading.tsx / error.tsx handle loading and error states. React Server Components (RSC), the default in the App Router, render on the server and send plain HTML to the client, reducing the JavaScript shipped to the browser and enabling direct database access without an API layer. Client Components are opt-in using the 'use client' directive and are necessary for interactivity, browser APIs, and React hooks. Data fetching in Server Components is done with async/await directly in the component tree. Route handlers (app/api/route.ts) replace the pages/api pattern and support all HTTP methods. The Server/Client component boundary is a key architectural decision: data fetching and sensitive operations belong in Server Components, while interactive UI belongs in Client Components. Next.js Image component automatically serves correctly-sized images, converts to WebP, and implements lazy loading. The metadata API provides a clean way to set SEO-relevant tags per page.""",
    },
]


def chunk_text(text: str, chunk_size: int = 512, overlap: int = 64) -> list:
    words = text.split()
def ingest_collections(model):
    print("Ingesting all knowledge base chunks...")
    db = {
        "ai_ml": AI_ML_CHUNKS,
        "backend": BACKEND_CHUNKS,
        "data_science": DATA_SCIENCE_CHUNKS,
        "fullstack": FULLSTACK_CHUNKS
    }
    
    for role, chunks in db.items():
        print(f"  Encoding {len(chunks)} chunks for '{role}'...")
        for chunk in chunks:
            emb = model.encode(chunk["text"])
            chunk["embedding"] = emb.tolist()
            
    os.makedirs(CHROMA_PERSIST_DIR, exist_ok=True)
    db_path = os.path.join(CHROMA_PERSIST_DIR, "vector_store.json")
    with open(db_path, "w") as f:
        json.dump(db, f)

def main():
    print("Initializing embedding model...")
    model = SentenceTransformer("all-MiniLM-L6-v2")

    ingest_collections(model)

    print("\nKnowledge base ingestion complete.")
    print(f"Vector store saved at: {os.path.join(CHROMA_PERSIST_DIR, 'vector_store.json')}")

if __name__ == "__main__":
    main()
